const datasets = {
  mip: {name:'Mip-NeRF 360', rows:[['3DGS','18.15','0.478','0.579'],['SS-3DGS','18.93','0.496','0.558'],['Mip-Splatting','18.87','0.493','0.564'],['SS-Mip-Splatting','18.93','0.497','0.557'],['Scaffold-GS','18.19','0.479','0.578'],['SS-Scaffold-GS','18.96','0.496','0.558'],['ControlGS (Ours)','19.33','0.524','0.528']], delta:['+0.37 dB over baseline','+0.028 over baseline','−0.030 below baseline']},
  synthetic: {name:'NeRF Synthetic', rows:[['3DGS','21.96','0.840','0.166'],['SS-3DGS','23.36','0.869','0.146'],['Mip-Splatting','23.17','0.862','0.152'],['SS-Mip-Splatting','23.37','0.870','0.145'],['Scaffold-GS','21.94','0.839','0.167'],['SS-Scaffold-GS','23.35','0.869','0.147'],['ControlGS (Ours)','23.59','0.871','0.137']], delta:['+0.24 dB over baseline','+0.002 over baseline','−0.010 below baseline']}
};
function selectDataset(key){const d=datasets[key]; document.querySelector('#dataset-label').textContent=d.name; document.querySelector('#quality-rows').innerHTML=d.rows.map((r,i)=>`<tr class="${i===6?'ours':''}"><th scope="row">${r[0]}</th>${r.slice(1).map(v=>`<td>${v}</td>`).join('')}</tr>`).join(''); ['psnr','ssim','lpips'].forEach((id,i)=>{document.getElementById(id).innerHTML=d.rows[6][i+1]+(i===0?' <small>dB</small>':'');document.getElementById(id+'-delta').textContent=d.delta[i]}); document.querySelectorAll('[data-dataset]').forEach(b=>{b.classList.toggle('active',b.dataset.dataset===key);b.setAttribute('aria-pressed',String(b.dataset.dataset===key))})}
document.querySelectorAll('[data-dataset]').forEach(b=>b.addEventListener('click',()=>selectDataset(b.dataset.dataset)));selectDataset('mip');
const menu=document.querySelector('.menu'), nav=document.querySelector('nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));
const dialog=document.querySelector('#image-dialog');document.querySelectorAll('.zoom').forEach(b=>b.addEventListener('click',()=>{const im=document.querySelector('#dialog-image');im.src=b.dataset.image;im.alt=b.querySelector('img').alt;dialog.showModal()}));document.querySelector('#close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
document.querySelector('#copy-citation').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(document.querySelector('#bibtex').textContent);document.querySelector('#copy-status').textContent='BibTeX copied to clipboard.'}catch{document.querySelector('#copy-status').textContent='Select the citation text above to copy it.'}});
fetch('abstract.txt').then(r=>{if(!r.ok)throw Error('Abstract unavailable');return r.text()}).then(t=>{const p=document.createElement('p');p.textContent=t;document.querySelector('#abstract-text').append(p)}).catch(()=>{document.querySelector('#abstract-text').textContent='Please see the paper for the full abstract.'});
